const choiceData = [
    {
        romaji: "a",
        hiragana: "あ",
        hiraganaImgURL:
            "https://res.cloudinary.com/dd1dw34dc/image/upload/v1676767333/hiragana_game/%E3%81%82_stroke_hgeopi.gif",
        katakana: "ア",
        katakanaImgURL: "",
        hiraganaRow: "あ行",
        katakanaRow: "ア行",
    },
    {
        romaji: "i",
        hiragana: "い",
        hiraganaImgURL: "",
        katakana: "イ",
        katakanaImgURL: "",
        hiraganaRow: "あ行",
        katakanaRow: "ア行",

    },
    {
        romaji: "u",
        hiragana: "う",
        hiraganaImgURL: "",
        katakana: "ウ",
        katakanaImgURL: "",
        hiraganaRow: "あ行",
        katakanaRow: "ア行",

    },
    {
        romaji: "e",
        hiragana: "え",
        hiraganaImgURL: "",
        katakana: "エ",
        katakanaImgURL: "",
        hiraganaRow: "あ行",
        katakanaRow: "ア行",

    },
    {
        romaji: "o",
        hiragana: "お",
        hiraganaImgURL: "",
        katakana: "オ",
        katakanaImgURL: "",
        hiraganaRow: "あ行",
        katakanaRow: "ア行",

    },
    {
        romaji: "ka",
        hiragana: "か",
        hiraganaImgURL: "",
        katakana: "カ",
        katakanaImgURL: "",
        hiraganaRow: "か行",
        katakanaRow: "カ行",
    },
    {
        romaji: "ga",
        hiragana: "が",
        hiraganaImgURL: "",
        katakana: "ガ",
        katakanaImgURL: "",
        hiraganaRow: "が行",
        katakanaRow: "ガ行",

    },
    {
        romaji: "ki",
        hiragana: "き",
        hiraganaImgURL: "",
        katakana: "キ",
        katakanaImgURL: "",
        hiraganaRow: "か行",
        katakanaRow: "カ行"
    },
    {
        romaji: "gi",
        hiragana: "ぎ",
        hiraganaImgURL: "",
        katakana: "ギ",
        katakanaImgURL: "",
        hiraganaRow: "が行",
        katakanaRow: "ガ行",
    },
    {
        romaji: "ku",
        hiragana: "く",
        hiraganaImgURL: "",
        katakana: "ク",
        katakanaImgURL: "",
        hiraganaRow: "か行",
        katakanaRow: "カ行"
    },
    {
        romaji: "gu",
        hiragana: "ぐ",
        hiraganaImgURL: "",
        katakana: "グ",
        katakanaImgURL: "",
        hiraganaRow: "が行",
        katakanaRow: "ガ行",
    },
    {
        romaji: "ke",
        hiragana: "け",
        hiraganaImgURL: "",
        katakana: "ケ",
        katakanaImg: "",
        hiraganaRow: "か行",
        katakanaRow: "カ行"
    },
    {
        romaji: "ge",
        hiragana: "げ",
        hiraganaImgURL: "",
        katakana: "ゲ",
        katakanaImgURL: "",
        hiraganaRow: "が行",
        katakanaRow: "ガ行",
    },
    {
        romaji: "ko",
        hiragana: "こ",
        hiraganaImgURL: "",
        katakana: "コ",
        katakanaImgURL: "",
        hiraganaRow: "か行",
        katakanaRow: "カ行"
    },
    {
        romaji: "go",
        hiragana: "ご",
        hiraganaImgURL: "",
        katakana: "ゴ",
        katakanaImgURL: "",
        hiraganaRow: "が行",
        katakanaRow: "ガ行",
    },
    {
        romaji: "sa",
        hiragana: "さ",
        hiraganaImgURL: "",
        katakana: "サ",
        katakanaImgURL: "",
        hiraganaRow: "さ行",
        katakanaRow: "サ行",
    },
    {
        romaji: "za",
        hiragana: "ざ",
        hiraganaImgURL: "",
        katakana: "ザ",
        katakanaImgURL: "",
        hiraganaRow: "ざ行",
        katakanaRow: "ザ行",
    },
    {
        romaji: "shi",
        hiragana: "し",
        hiraganaImgURL: "",
        katakana: "シ",
        katakanaImgURL: "",
        hiraganaRow: "さ行",
        katakanaRow: "サ行",
    },
    {
        romaji: "ji",
        hiragana: "じ",
        hiraganaImgURL: "",
        katakana: "ジ",
        katakanaImgURL: "",
        hiraganaRow: "ざ行",
        katakanaRow: "ザ行",
    },
    {
        romaji: "su",
        hiragana: "す",
        hiraganaImgURL: "",
        katakana: "ス",
        katakanaImgURL: "",
        hiraganaRow: "さ行",
        katakanaRow: "サ行",
    },
    {
        romaji: "zu",
        hiragana: "ず",
        hiraganaImgURL: "",
        katakana: "ズ",
        katakanaImgURL: "",
        hiraganaRow: "ざ行",
        katakanaRow: "ザ行",
    },
    {
        romaji: "se",
        hiragana: "せ",
        hiraganaImgURL: "",
        katakana: "セ",
        katakanaImgURL: "",
        hiraganaRow: "さ行",
        katakanaRow: "サ行",
    },
    {
        romaji: "ze",
        hiragana: "ぜ",
        hiraganaImgURL: "",
        katakana: "ゼ",
        katakanaImgURL: "",
        hiraganaRow: "ざ行",
        katakanaRow: "ザ行",
    },
    {
        romaji: "so",
        hiragana: "そ",
        hiraganaImgURL: "",
        katakana: "ソ",
        katakanaImgURL: "",
        hiraganaRow: "さ行",
        katakanaRow: "サ行",
    },
    {
        romaji: "zo",
        hiragana: "ぞ",
        hiraganaImgURL: "",
        katakana: "ゾ",
        katakanaImgURL: "",
        hiraganaRow: "ざ行",
        katakanaRow: "ザ行",
    },
    {
        romaji: "ta",
        hiragana: "た",
        hiraganaImgURL: "",
        katakana: "タ",
        katakanaImgURL: "",
        hiraganaRow: "た行",
        katakanaRow: "タ行",
    },
    {
        romaji: "da",
        hiragana: "だ",
        hiraganaImgURL: "",
        katakana: "ダ",
        katakanaImgURL: "",
        hiraganaRow: "だ行",
        katakanaRow: "ダ行",
    },
    {
        romaji: "chi",
        hiragana: "ち",
        hiraganaImgURL: "",
        katakana: "チ",
        katakanaImgURL: "",
        hiraganaRow: "た行",
        katakanaRow: "タ行",
    },
    {
        romaji: "di",
        hiragana: "ぢ",
        hiraganaImgURL: "",
        katakana: "ヂ",
        katakanaImgURL: "",
        hiraganaRow: "だ行",
        katakanaRow: "ダ行",
    },
    {
        romaji: "tsu",
        hiragana: "つ",
        hiraganaImgURL: "",
        katakana: "ツ",
        katakanaImgURL: "",
        hiraganaRow: "た行",
        katakanaRow: "タ行",
    },
    {
        romaji: "du",
        hiragana: "づ",
        hiraganaImgURL: "",
        katakana: "ヅ",
        katakanaImgURL: "",
        hiraganaRow: "だ行",
        katakanaRow: "ダ行",
    },
    {
        romaji: "te",
        hiragana: "て",
        hiraganaImgURL: "",
        katakana: "テ",
        katakanaImgURL: "",
        hiraganaRow: "た行",
        katakanaRow: "タ行",
    },
    {
        romaji: "de",
        hiragana: "で",
        hiraganaImgURL: "",
        katakana: "デ",
        katakanaImgURL: "",
        hiraganaRow: "だ行",
        katakanaRow: "ダ行",
    },
    {
        romaji: "to",
        hiragana: "と",
        hiraganaImgURL: "",
        katakana: "ト",
        katakanaImgURL: "",
        hiraganaRow: "た行",
        katakanaRow: "タ行",
    },
    {
        romaji: "do",
        hiragana: "ど",
        hiraganaImgURL: "",
        katakana: "ド",
        katakanaImgURL: "",
        hiraganaRow: "だ行",
        katakanaRow: "ダ行",
    },
    {
        romaji: "na",
        hiragana: "な",
        hiraganaImgURL: "",
        katakana: "ナ",
        katakanaImgURL: "",
        hiraganaRow: "な行",
        katakanaRow: "ナ行",
    },
    {
        romaji: "ni",
        hiragana: "に",
        hiraganaImgURL: "",
        katakana: "ニ",
        katakanaImgURL: "",
        hiraganaRow: "な行",
        katakanaRow: "ナ行",
    },
    {
        romaji: "nu",
        hiragana: "ぬ",
        hiraganaImgURL: "",
        katakana: "ヌ",
        katakanaImgURL: "",
        hiraganaRow: "な行",
        katakanaRow: "ナ行",
    },
    {
        romaji: "ne",
        hiragana: "ね",
        hiraganaImgURL: "",
        katakana: "ネ",
        katakanaImgURL: "",
        hiraganaRow: "な行",
        katakanaRow: "ナ行",
    },
    {
        romaji: "no",
        hiragana: "の",
        hiraganaImgURL: "",
        katakana: "ノ",
        katakanaImgURL: "",
        hiraganaRow: "な行",
        katakanaRow: "ナ行",
    },
    {
        romaji: "ha",
        hiragana: "は",
        hiraganaImgURL: "",
        katakana: "ハ",
        katakanaImgURL: "",
        hiraganaRow: "は行",
        katakanaRow: "ハ行",
    },
    {
        romaji: "ba",
        hiragana: "ば",
        hiraganaImgURL: "",
        katakana: "バ",
        katakanaImgURL: "",
        hiraganaRow: "ば行",
        katakanaRow: "バ行",
    },
    {
        romaji: "pa",
        hiragana: "ぱ",
        hiraganaImgURL: "",
        katakana: "パ",
        katakanaImgURL: "",
        hiraganaRow: "ぱ行",
        katakanaRow: "パ行",
    },
    {
        romaji: "hi",
        hiragana: "ひ",
        hiraganaImgURL: "",
        katakana: "ヒ",
        katakanaImgURL: "",
        hiraganaRow: "は行",
        katakanaRow: "ハ行",
    },
    {
        romaji: "bi",
        hiragana: "び",
        hiraganaImgURL: "",
        katakana: "ビ",
        katakanaImgURL: "",
        hiraganaRow: "ば行",
        katakanaRow: "バ行",
    },
    {
        romaji: "pi",
        hiragana: "ぴ",
        hiraganaImgURL: "",
        katakana: "ピ",
        katakanaImgURL: "",
        hiraganaRow: "ぱ行",
        katakanaRow: "パ行",
    },
    {
        romaji: "hu",
        hiragana: "ふ",
        hiraganaImgURL: "",
        katakana: "フ",
        katakanaImgURL: "",
        hiraganaRow: "は行",
        katakanaRow: "ハ行",
    },
    {
        romaji: "bu",
        hiragana: "ぶ",
        hiraganaImgURL: "",
        katakana: "ブ",
        katakanaImgURL: "",
        hiraganaRow: "ば行",
        katakanaRow: "バ行",
    },
    {
        romaji: "pu",
        hiragana: "ぷ",
        hiraganaImgURL: "",
        katakana: "プ",
        katakanaImgURL: "",
        hiraganaRow: "ぱ行",
        katakanaRow: "パ行",
    },
    {
        romaji: "he",
        hiragana: "へ",
        hiraganaImgURL: "",
        katakana: "ヘ",
        katakanaImgURL: "",
        hiraganaRow: "は行",
        katakanaRow: "ハ行",
    },
    {
        romaji: "be",
        hiragana: "べ",
        hiraganaImgURL: "",
        katakana: "ベ",
        katakanaImgURL: "",
        hiraganaRow: "ば行",
        katakanaRow: "バ行",
    },
    {
        romaji: "pe",
        hiragana: "ぺ",
        hiraganaImgURL: "",
        katakana: "ペ",
        katakanaImgURL: "",
        hiraganaRow: "ぱ行",
        katakanaRow: "パ行",
    },
    {
        romaji: "ho",
        hiragana: "ほ",
        hiraganaImgURL: "",
        katakana: "ホ",
        katakanaImgURL: "",
        hiraganaRow: "は行",
        katakanaRow: "ハ行",
    },
    {
        romaji: "bo",
        hiragana: "ぼ",
        hiraganaImgURL: "",
        katakana: "ボ",
        katakanaImgURL: "",
        hiraganaRow: "ば行",
        katakanaRow: "バ行",
    },
    {
        romaji: "po",
        hiragana: "ぽ",
        hiraganaImgURL: "",
        katakana: "ポ",
        katakanaImgURL: "",
        hiraganaRow: "ぱ行",
        katakanaRow: "パ行",
    },
    {
        romaji: "ma",
        hiragana: "ま",
        hiraganaImgURL: "",
        katakana: "マ",
        katakanaImgURL: "",
        hiraganaRow: "ま行",
        katakanaRow: "マ行",
    },
    {
        romaji: "mi",
        hiragana: "み",
        hiraganaImgURL: "",
        katakana: "ミ",
        katakanaImgURL: "",
        hiraganaRow: "ま行",
        katakanaRow: "マ行",
    },
    {
        romaji: "mu",
        hiragana: "む",
        hiraganaImgURL: "",
        katakana: "ム",
        katakanaImgURL: "",
        hiraganaRow: "ま行",
        katakanaRow: "マ行",
    },
    {
        romaji: "me",
        hiragana: "め",
        hiraganaImgURL: "",
        katakana: "メ",
        katakanaImgURL: "",
        hiraganaRow: "ま行",
        katakanaRow: "マ行",
    },
    {
        romaji: "mo",
        hiragana: "も",
        hiraganaImgURL: "",
        katakana: "モ",
        katakanaImgURL: "",
        hiraganaRow: "ま行",
        katakanaRow: "マ行",
    },
    {
        romaji: "ya",
        hiragana: "や",
        hiraganaImgURL: "",
        katakana: "ヤ",
        katakanaImgURL: "",
        hiraganaRow: "や行",
        katakanaRow: "ヤ行",
    },
    {
        romaji: "yu",
        hiragana: "ゆ",
        hiraganaImgURL: "",
        katakana: "ユ",
        katakanaImgURL: "",
        hiraganaRow: "や行",
        katakanaRow: "ヤ行",
    },
    {
        romaji: "yo",
        hiragana: "よ",
        hiraganaImgURL: "",
        katakana: "ヨ",
        katakanaImgURL: "",
        hiraganaRow: "や行",
        katakanaRow: "ヤ行",
    },
    {
        romaji: "ra",
        hiragana: "ら",
        hiraganaImgURL: "",
        katakana: "ラ",
        katakanaImgURL: "",
        hiraganaRow: "ら行",
        katakanaRow: "ラ行",
    },
    {
        romaji: "ri",
        hiragana: "り",
        hiraganaImgURL: "",
        katakana: "リ",
        katakanaImgURL: "",
        hiraganaRow: "ら行",
        katakanaRow: "ラ行",
    },
    {
        romaji: "ru",
        hiragana: "る",
        hiraganaImgURL: "",
        katakana: "ル",
        katakanaImgURL: "",
        hiraganaRow: "ら行",
        katakanaRow: "ラ行",
    },
    {
        romaji: "re",
        hiragana: "れ",
        hiraganaImgURL: "",
        katakana: "レ",
        katakanaImgURL: "",
        hiraganaRow: "ら行",
        katakanaRow: "ラ行",
    },
    {
        romaji: "ro",
        hiragana: "ろ",
        hiraganaImgURL: "",
        katakana: "ロ",
        katakanaImgURL: "",
        hiraganaRow: "ら行",
        katakanaRow: "ラ行",
    },
    {
        romaji: "wa",
        hiragana: "わ",
        hiraganaImgURL: "",
        katakana: "ワ",
        katakanaImgURL: "",
        hiraganaRow: "わ行",
        katakanaRow: "ワ行",
    },
    {
        romaji: "wo",
        hiragana: "を",
        hiraganaImgURL: "",
        katakana: "ヲ",
        katakanaImgURL: "",
        hiraganaRow: "わ行",
        katakanaRow: "ワ行",
    },
    {
        romaji: "n",
        hiragana: "ん",
        hiraganaImgURL: "",
        katakana: "ン",
        katakanaImgURL: "",
        hiraganaRow: "わ行",
        katakanaRow: "ワ行",
    }
];


export default choiceData;