const choiceData = [
    {
        romaji: "a",
        hiragana: "あ",
        hiraganaImgURL:
            "https://res.cloudinary.com/dd1dw34dc/image/upload/v1676767333/hiragana_game/%E3%81%82_stroke_hgeopi.gif",
        katakana: "ア",
        katakanaImgURL: "",
        row: "あ行",
    },
    {
        romaji: "i",
        hiragana: "い",
        hiraganaImgURL: "",
        katakana: "イ",
        katakanaImgURL: "",
        row: "あ行",

    },
    {
        romaji: "u",
        hiragana: "う",
        hiraganaImgURL: "",
        katakana: "ウ",
        katakanaImgURL: "",
        row: "あ行",

    },
    {
        romaji: "e",
        hiragana: "え",
        hiraganaImgURL: "",
        katakana: "エ",
        katakanaImgURL: "",
        row: "あ行",

    },
    {
        romaji: "o",
        hiragana: "お",
        hiraganaImgURL: "",
        katakana: "オ",
        katakanaImgURL: "",
        row: "あ行",

    },
    {
        romaji: "ka",
        hiragana: "か",
        hiraganaImgURL: "",
        katakana: "カ",
        katakanaImgURL: "",
        row: "か行",
    },
    // {
    //     romaji: "ga",
    //     hiragana: "が",
    //     hiraganaImgURL: "",
    //     katakana: "ガ",
    //     katakanaImgURL: "",
    //     row: "が行",
    //
    // },
    {
        romaji: "ki",
        hiragana: "き",
        hiraganaImgURL: "",
        katakana: "キ",
        katakanaImgURL: "",
        row: "か行",
    },
    // {
    //     romaji: "gi",
    //     hiragana: "ぎ",
    //     hiraganaImgURL: "",
    //     katakana: "ギ",
    //     katakanaImgURL: "",
    //     row: "が行",
    // },
    {
        romaji: "ku",
        hiragana: "く",
        hiraganaImgURL: "",
        katakana: "ク",
        katakanaImgURL: "",
        row: "か行",
    },
    // {
    //     romaji: "gu",
    //     hiragana: "ぐ",
    //     hiraganaImgURL: "",
    //     katakana: "グ",
    //     katakanaImgURL: "",
    //     row: "が行",
    // },
    {
        romaji: "ke",
        hiragana: "け",
        hiraganaImgURL: "",
        katakana: "ケ",
        katakanaImg: "",
        row: "か行",
    },
    // {
    //     romaji: "ge",
    //     hiragana: "げ",
    //     hiraganaImgURL: "",
    //     katakana: "ゲ",
    //     katakanaImgURL: "",
    //     row: "が行",
    // },
    {
        romaji: "ko",
        hiragana: "こ",
        hiraganaImgURL: "",
        katakana: "コ",
        katakanaImgURL: "",
        row: "か行",
    },
    // {
    //     romaji: "go",
    //     hiragana: "ご",
    //     hiraganaImgURL: "",
    //     katakana: "ゴ",
    //     katakanaImgURL: "",
    //     row: "が行",
    // },
    // {
    //     romaji: "sa",
    //     hiragana: "さ",
    //     hiraganaImgURL: "",
    //     katakana: "サ",
    //     katakanaImgURL: "",
    //     row: "さ行",
    // },
    // {
    //     romaji: "za",
    //     hiragana: "ざ",
    //     hiraganaImgURL: "",
    //     katakana: "ザ",
    //     katakanaImgURL: "",
    //     row: "ざ行",
    // },
    // {
    //     romaji: "shi",
    //     hiragana: "し",
    //     hiraganaImgURL: "",
    //     katakana: "シ",
    //     katakanaImgURL: "",
    //     row: "さ行",
    // },
    // {
    //     romaji: "ji",
    //     hiragana: "じ",
    //     hiraganaImgURL: "",
    //     katakana: "ジ",
    //     katakanaImgURL: "",
    //     row: "ざ行",
    // },
    // {
    //     romaji: "su",
    //     hiragana: "す",
    //     hiraganaImgURL: "",
    //     katakana: "ス",
    //     katakanaImgURL: "",
    //     row: "さ行",
    // },
    // {
    //     romaji: "zu",
    //     hiragana: "ず",
    //     hiraganaImgURL: "",
    //     katakana: "ズ",
    //     katakanaImgURL: "",
    //     row: "ざ行",
    // },
    // {
    //     romaji: "se",
    //     hiragana: "せ",
    //     hiraganaImgURL: "",
    //     katakana: "セ",
    //     katakanaImgURL: "",
    //     row: "さ行",
    // },
    // {
    //     romaji: "ze",
    //     hiragana: "ぜ",
    //     hiraganaImgURL: "",
    //     katakana: "ゼ",
    //     katakanaImgURL: "",
    //     row: "ざ行",
    // },
    // {
    //     romaji: "so",
    //     hiragana: "そ",
    //     hiraganaImgURL: "",
    //     katakana: "ソ",
    //     katakanaImgURL: "",
    //     row: "さ行",
    // },
    // {
    //     romaji: "zo",
    //     hiragana: "ぞ",
    //     hiraganaImgURL: "",
    //     katakana: "ゾ",
    //     katakanaImgURL: "",
    //     row: "ざ行",
    // },
    // {
    //     romaji: "ta",
    //     hiragana: "た",
    //     hiraganaImgURL: "",
    //     katakana: "タ",
    //     katakanaImgURL: "",
    //     row: "た行",
    // },
    // {
    //     romaji: "da",
    //     hiragana: "だ",
    //     hiraganaImgURL: "",
    //     katakana: "ダ",
    //     katakanaImgURL: "",
    // },
    // {
    //     romaji: "chi",
    //     hiragana: "ち",
    //     hiraganaImgURL: "",
    //     katakana: "チ",
    //     katakanaImgURL: "",
    //     row: "た行",
    // },
    // {
    //     romaji: "di",
    //     hiragana: "ぢ",
    //     hiraganaImgURL: "",
    //     katakana: "ヂ",
    //     katakanaImgURL: "",
    //     row: "だ行",
    // },
    // {
    //     romaji: "tsu",
    //     hiragana: "つ",
    //     hiraganaImgURL: "",
    //     katakana: "ツ",
    //     katakanaImgURL: "",
    //     row: "た行",
    // },
    // {
    //     romaji: "du",
    //     hiragana: "づ",
    //     hiraganaImgURL: "",
    //     katakana: "ヅ",
    //     katakanaImgURL: "",
    //     row: "だ行",
    // },
    // {
    //     romaji: "te",
    //     hiragana: "て",
    //     hiraganaImgURL: "",
    //     katakana: "テ",
    //     katakanaImgURL: "",
    //     row: "た行",
    // },
    // {
    //     romaji: "de",
    //     hiragana: "で",
    //     hiraganaImgURL: "",
    //     katakana: "デ",
    //     katakanaImgURL: "",
    //     row: "だ行",
    // },
    // {
    //     romaji: "to",
    //     hiragana: "と",
    //     hiraganaImgURL: "",
    //     katakana: "ト",
    //     katakanaImgURL: "",
    //     row: "た行",
    // },
    // {
    //     romaji: "do",
    //     hiragana: "ど",
    //     hiraganaImgURL: "",
    //     katakana: "ド",
    //     katakanaImgURL: "",
    //     row: "だ行",
    // },
    // {
    //     romaji: "na",
    //     hiragana: "な",
    //     hiraganaImgURL: "",
    //     katakana: "ナ",
    //     katakanaImgURL: "",
    //     row: "な行",
    // },
    // {
    //     romaji: "ni",
    //     hiragana: "に",
    //     hiraganaImgURL: "",
    //     katakana: "ニ",
    //     katakanaImgURL: "",
    //     row: "な行",
    // },
    // {
    //     romaji: "nu",
    //     hiragana: "ぬ",
    //     hiraganaImgURL: "",
    //     katakana: "ヌ",
    //     katakanaImgURL: "",
    //     row: "な行",
    // },
    // {
    //     romaji: "ne",
    //     hiragana: "ね",
    //     hiraganaImgURL: "",
    //     katakana: "ネ",
    //     katakanaImgURL: "",
    //     row: "な行",
    // },
    // {
    //     romaji: "no",
    //     hiragana: "の",
    //     hiraganaImgURL: "",
    //     katakana: "ノ",
    //     katakanaImgURL: "",
    //     row: "な行",
    // },
    // {
    //     romaji: "ha",
    //     hiragana: "は",
    //     hiraganaImgURL: "",
    //     katakana: "ハ",
    //     katakanaImgURL: "",
    //     row: "は行",
    // },
    // {
    //     romaji: "ba",
    //     hiragana: "ば",
    //     hiraganaImgURL: "",
    //     katakana: "バ",
    //     katakanaImgURL: "",
    //     row: "ば行",
    // },
    // {
    //     romaji: "pa",
    //     hiragana: "ぱ",
    //     hiraganaImgURL: "",
    //     katakana: "パ",
    //     katakanaImgURL: "",
    //     row: "ぱ行",
    // },
    // {
    //     romaji: "hi",
    //     hiragana: "ひ",
    //     hiraganaImgURL: "",
    //     katakana: "ヒ",
    //     katakanaImgURL: "",
    //     row: "は行",
    // },
    // {
    //     romaji: "bi",
    //     hiragana: "び",
    //     hiraganaImgURL: "",
    //     katakana: "ビ",
    //     katakanaImgURL: "",
    //     row: "ば行",
    // },
    // {
    //     romaji: "pi",
    //     hiragana: "ぴ",
    //     hiraganaImgURL: "",
    //     katakana: "ピ",
    //     katakanaImgURL: "",
    //     row: "ぱ行",
    // },
    // {
    //     romaji: "hu",
    //     hiragana: "ふ",
    //     hiraganaImgURL: "",
    //     katakana: "フ",
    //     katakanaImgURL: "",
    //     row: "は行",
    // },
    // {
    //     romaji: "bu",
    //     hiragana: "ぶ",
    //     hiraganaImgURL: "",
    //     katakana: "ブ",
    //     katakanaImgURL: "",
    //     row: "ば行",
    // },
    // {
    //     romaji: "pu",
    //     hiragana: "ぷ",
    //     hiraganaImgURL: "",
    //     katakana: "プ",
    //     katakanaImgURL: "",
    //     row: "ぱ行",
    // },
    // {
    //     romaji: "he",
    //     hiragana: "へ",
    //     hiraganaImgURL: "",
    //     katakana: "ヘ",
    //     katakanaImgURL: "",
    //     row: "は行",
    // },
    // {
    //     romaji: "be",
    //     hiragana: "べ",
    //     hiraganaImgURL: "",
    //     katakana: "ベ",
    //     katakanaImgURL: "",
    //     row: "ば行",
    // },
    // {
    //     romaji: "pe",
    //     hiragana: "ぺ",
    //     hiraganaImgURL: "",
    //     katakana: "ペ",
    //     katakanaImgURL: "",
    //     row: "ぱ行",
    // },
    // {
    //     romaji: "ho",
    //     hiragana: "ほ",
    //     hiraganaImgURL: "",
    //     katakana: "ホ",
    //     katakanaImgURL: "",
    //     row: "は行",
    // },
    // {
    //     romaji: "bo",
    //     hiragana: "ぼ",
    //     hiraganaImgURL: "",
    //     katakana: "ボ",
    //     katakanaImgURL: "",
    //     row: "ば行",
    // },
    // {
    //     romaji: "po",
    //     hiragana: "ぽ",
    //     hiraganaImgURL: "",
    //     katakana: "ポ",
    //     katakanaImgURL: "",
    //     row: "ぱ行",
    // },
    // {
    //     romaji: "ma",
    //     hiragana: "ま",
    //     hiraganaImgURL: "",
    //     katakana: "マ",
    //     katakanaImgURL: "",
    //     row: "ま行",
    // },
    // {
    //     romaji: "mi",
    //     hiragana: "み",
    //     hiraganaImgURL: "",
    //     katakana: "ミ",
    //     katakanaImgURL: "",
    //     row: "ま行",
    // },
    // {
    //     romaji: "mu",
    //     hiragana: "む",
    //     hiraganaImgURL: "",
    //     katakana: "ム",
    //     katakanaImgURL: "",
    //     row: "ま行",
    // },
    // {
    //     romaji: "me",
    //     hiragana: "め",
    //     hiraganaImgURL: "",
    //     katakana: "メ",
    //     katakanaImgURL: "",
    //     row: "ま行",
    // },
    // {
    //     romaji: "mo",
    //     hiragana: "も",
    //     hiraganaImgURL: "",
    //     katakana: "モ",
    //     katakanaImgURL: "",
    //     row: "ま行",
    // },
    // {
    //     romaji: "ya",
    //     hiragana: "や",
    //     hiraganaImgURL: "",
    //     katakana: "ヤ",
    //     katakanaImgURL: "",
    //     row: "や行",
    // },
    // {
    //     romaji: "yu",
    //     hiragana: "ゆ",
    //     hiraganaImgURL: "",
    //     katakana: "ユ",
    //     katakanaImgURL: "",
    //     row: "や行",
    // },
    // {
    //     romaji: "yo",
    //     hiragana: "よ",
    //     hiraganaImgURL: "",
    //     katakana: "ヨ",
    //     katakanaImgURL: "",
    //     row: "や行",
    // },
    // {
    //     romaji: "ra",
    //     hiragana: "ら",
    //     hiraganaImgURL: "",
    //     katakana: "ラ",
    //     katakanaImgURL: "",
    //     row: "ら行",
    // },
    // {
    //     romaji: "ri",
    //     hiragana: "り",
    //     hiraganaImgURL: "",
    //     katakana: "リ",
    //     katakanaImgURL: "",
    //     row: "ら行",
    // },
    // {
    //     romaji: "ru",
    //     hiragana: "る",
    //     hiraganaImgURL: "",
    //     katakana: "ル",
    //     katakanaImgURL: "",
    //     row: "ら行",
    // },
    // {
    //     romaji: "re",
    //     hiragana: "れ",
    //     hiraganaImgURL: "",
    //     katakana: "レ",
    //     katakanaImgURL: "",
    //     row: "ら行",
    // },
    // {
    //     romaji: "ro",
    //     hiragana: "ろ",
    //     hiraganaImgURL: "",
    //     katakana: "ロ",
    //     katakanaImgURL: "",
    //     row: "ら行",
    // },
    // {
    //     romaji: "wa",
    //     hiragana: "わ",
    //     hiraganaImgURL: "",
    //     katakana: "ワ",
    //     katakanaImgURL: "",
    //     row: "わ行",
    // },
    // {
    //     romaji: "wo",
    //     hiragana: "を",
    //     hiraganaImgURL: "",
    //     katakana: "ヲ",
    //     katakanaImgURL: "",
    //     row: "わ行",
    // },
    // {
    //     romaji: "n",
    //     hiragana: "ん",
    //     hiraganaImgURL: "",
    //     katakana: "ン",
    //     katakanaImgURL: "",
    //     row: "わ行",
    // }
];


export default choiceData;