const choiceData = [
    {
        romaji: "a",
        hiragana: "あ",
        hiraganaImgURL:
            "https://res.cloudinary.com/dd1dw34dc/image/upload/v1676767333/hiragana_game/%E3%81%82_stroke_hgeopi.gif",
        katakana: "ア",
        katakanaImgURL: "path/to/ア/image",
    },
    {
        romaji: "i",
        hiragana: "い",
        hiraganaImgURL: "path/to/い/image",
        katakana: "イ",
        katakanaImgURL: "path/to/イ/image",
    },
    {
        romaji: "u",
        hiragana: "う",
        hiraganaImgURL: "path/to/う/image",
        katakana: "ウ",
        katakanaImgURL: "path/to/ウ/image",
    },
    {
        romaji: "e",
        hiragana: "え",
        hiraganaImgURL: "path/to/え/image",
        katakana: "エ",
        katakanaImgURL: "path/to/エ/image",
    },
    {
        romaji: "o",
        hiragana: "お",
        hiraganaImgURL: "path/to/お/image",
        katakana: "オ",
        katakanaImgURL: "path/to/オ/image",
    },
    {
        romaji: "ka",
        hiragana: "か",
        hiraganaImgURL: "path/to/か/image",
        katakana: "カ",
        katakanaImgURL: "path/to/カ/image",
    },
    {
        romaji: "ga",
        hiragana: "が",
        hiraganaImgURL: "path/to/が/image",
        katakana: "ガ",
        katakanaImgURL: "path/to/ガ/image",
    },
    {
        romaji: "ki",
        hiragana: "き",
        hiraganaImgURL: "path/to/き/image",
        katakana: "キ",
        katakanaImgURL: "path/to/キ/image",
    },
    {
        romaji: "gi",
        hiragana: "ぎ",
        hiraganaImgURL: "path/to/ぎ/image",
        katakana: "ギ",
        katakanaImgURL: "path/to/ギ/image",
    },
    {
        romaji: "ku",
        hiragana: "く",
        hiraganaImgURL: "path/to/く/image",
        katakana: "ク",
        katakanaImgURL: "path/to/ク/image",
    },
    {
        romaji: "gu",
        hiragana: "ぐ",
        hiraganaImgURL: "path/to/ぐ/image",
        katakana: "グ",
        katakanaImgURL: "path/to/グ/image",
    },
    {
        romaji: "ke",
        hiragana: "け",
        hiraganaImgURL: "path/to/け/image",
        katakana: "ケ",
        katakanaImg: "path/to/ケ/image"
    },
    {
        romaji: "ge",
        hiragana: "げ",
        hiraganaImgURL: "path/to/げ/image",
        katakana: "ゲ",
        katakanaImgURL: "path/to/ゲ/image",
    },
    {
        romaji: "ko",
        hiragana: "こ",
        hiraganaImgURL: "path/to/こ/image",
        katakana: "コ",
        katakanaImgURL: "path/to/コ/image",
    },
    {
        romaji: "go",
        hiragana: "ご",
        hiraganaImgURL: "path/to/ご/image",
        katakana: "ゴ",
        katakanaImgURL: "path/to/ゴ/image",
    },
    {
        romaji: "sa",
        hiragana: "さ",
        hiraganaImgURL: "path/to/さ/image",
        katakana: "サ",
        katakanaImgURL: "path/to/サ/image",
    },
    {
        romaji: "za",
        hiragana: "ざ",
        hiraganaImgURL: "path/to/ざ/image",
        katakana: "ザ",
        katakanaImgURL: "path/to/ザ/image",
    },
    {
        romaji: "shi",
        hiragana: "し",
        hiraganaImgURL: "path/to/し/image",
        katakana: "シ",
        katakanaImgURL: "path/to/シ/image",
    },
    {
        romaji: "ji",
        hiragana: "じ",
        hiraganaImgURL: "path/to/じ/image",
        katakana: "ジ",
        katakanaImgURL: "path/to/ジ/image",
    },
    {
        romaji: "su",
        hiragana: "す",
        hiraganaImgURL: "path/to/す/image",
        katakana: "ス",
        katakanaImgURL: "path/to/ス/image",
    },
    {
        romaji: "zu",
        hiragana: "ず",
        hiraganaImgURL: "path/to/ず/image",
        katakana: "ズ",
        katakanaImgURL: "path/to/ズ/image",
    },
    {
        romaji: "se",
        hiragana: "せ",
        hiraganaImgURL: "path/to/せ/image",
        katakana: "セ",
        katakanaImgURL: "path/to/セ/image",
    },
    {
        romaji: "ze",
        hiragana: "ぜ",
        hiraganaImgURL: "path/to/ぜ/image",
        katakana: "ゼ",
        katakanaImgURL: "path/to/ゼ/image",
    },
    {
        romaji: "so",
        hiragana: "そ",
        hiraganaImgURL: "path/to/そ/image",
        katakana: "ソ",
        katakanaImgURL: "path/to/ソ/image",
    },
    {
        romaji: "zo",
        hiragana: "ぞ",
        hiraganaImgURL: "path/to/ぞ/image",
        katakana: "ゾ",
        katakanaImgURL: "path/to/ゾ/image",
    },
    {
        romaji: "ta",
        hiragana: "た",
        hiraganaImgURL: "path/to/た/image",
        katakana: "タ",
        katakanaImgURL: "path/to/タ/image",
    },
    {
        romaji: "da",
        hiragana: "だ",
        hiraganaImgURL: "path/to/だ/image",
        katakana: "ダ",
        katakanaImgURL: "path/to/ダ/image",
    },
    {
        romaji: "chi",
        hiragana: "ち",
        hiraganaImgURL: "path/to/ち/image",
        katakana: "チ",
        katakanaImgURL: "path/to/チ/image",
    },
    {
        romaji: "di",
        hiragana: "ぢ",
        hiraganaImgURL: "path/to/ぢ/image",
        katakana: "ヂ",
        katakanaImgURL: "path/to/ヂ/image",
    },
    {
        romaji: "tsu",
        hiragana: "つ",
        hiraganaImgURL: "path/to/つ/image",
        katakana: "ツ",
        katakanaImgURL: "path/to/ツ/image",
    },
    {
        romaji: "du",
        hiragana: "づ",
        hiraganaImgURL: "path/to/づ/image",
        katakana: "ヅ",
        katakanaImgURL: "path/to/ヅ/image",
    },
    {
        romaji: "te",
        hiragana: "て",
        hiraganaImgURL: "path/to/て/image",
        katakana: "テ",
        katakanaImgURL: "path/to/テ/image",
    },
    {
        romaji: "de",
        hiragana: "で",
        hiraganaImgURL: "path/to/で/image",
        katakana: "デ",
        katakanaImgURL: "path/to/デ/image",
    },
    {
        romaji: "to",
        hiragana: "と",
        hiraganaImgURL: "path/to/と/image",
        katakana: "ト",
        katakanaImgURL: "path/to/ト/image",
    },
    {
        romaji: "do",
        hiragana: "ど",
        hiraganaImgURL: "path/to/ど/image",
        katakana: "ド",
        katakanaImgURL: "path/to/ド/image",
    },
    {
        romaji: "na",
        hiragana: "な",
        hiraganaImgURL: "path/to/な/image",
        katakana: "ナ",
        katakanaImgURL: "path/to/ナ/image",
    },
    {
        romaji: "ni",
        hiragana: "に",
        hiraganaImgURL: "path/to/に/image",
        katakana: "ニ",
        katakanaImgURL: "path/to/ニ/image",
    },
    {
        romaji: "nu",
        hiragana: "ぬ",
        hiraganaImgURL: "path/to/ぬ/image",
        katakana: "ヌ",
        katakanaImgURL: "path/to/ヌ/image",
    },
    {
        romaji: "ne",
        hiragana: "ね",
        hiraganaImgURL: "path/to/ね/image",
        katakana: "ネ",
        katakanaImgURL: "path/to/ネ/image",
    },
    {
        romaji: "no",
        hiragana: "の",
        hiraganaImgURL: "path/to/の/image",
        katakana: "ノ",
        katakanaImgURL: "path/to/ノ/image",
    },
    {
        romaji: "ha",
        hiragana: "は",
        hiraganaImgURL: "path/to/は/image",
        katakana: "ハ",
        katakanaImgURL: "path/to/ハ/image",
    },
    {
        romaji: "ba",
        hiragana: "ば",
        hiraganaImgURL: "path/to/ば/image",
        katakana: "バ",
        katakanaImgURL: "path/to/バ/image",
    },
    {
        romaji: "pa",
        hiragana: "ぱ",
        hiraganaImgURL: "path/to/ぱ/image",
        katakana: "パ",
        katakanaImgURL: "path/to/パ/image",
    },
    {
        romaji: "hi",
        hiragana: "ひ",
        hiraganaImgURL: "path/to/ひ/image",
        katakana: "ヒ",
        katakanaImgURL: "path/to/ヒ/image",
    },
    {
        romaji: "bi",
        hiragana: "び",
        hiraganaImgURL: "path/to/び/image",
        katakana: "ビ",
        katakanaImgURL: "path/to/ビ/image",
    },
    {
        romaji: "pi",
        hiragana: "ぴ",
        hiraganaImgURL: "path/to/ぴ/image",
        katakana: "ピ",
        katakanaImgURL: "path/to/ピ/image",
    },
    {
        romaji: "hu",
        hiragana: "ふ",
        hiraganaImgURL: "path/to/ふ/image",
        katakana: "フ",
        katakanaImgURL: "path/to/フ/image",
    },
    {
        romaji: "bu",
        hiragana: "ぶ",
        hiraganaImgURL: "path/to/ぶ/image",
        katakana: "ブ",
        katakanaImgURL: "path/to/ブ/image",
    },
    {
        romaji: "he",
        hiragana: "へ",
        hiraganaImgURL: "path/to/へ/image",
        katakana: "ヘ",
        katakanaImgURL: "path/to/ヘ/image",
    },
    {
        romaji: "be",
        hiragana: "べ",
        hiraganaImgURL: "path/to/べ/image",
        katakana: "ベ",
        katakanaImgURL: "path/to/ベ/image",
    },
    {
        romaji: "pe",
        hiragana: "ぺ",
        hiraganaImgURL: "path/to/ぺ/image",
        katakana: "ペ",
        katakanaImgURL: "path/to/ペ/image",
    },
    {
        romaji: "ho",
        hiragana: "ほ",
        hiraganaImgURL: "path/to/ほ/image",
        katakana: "ホ",
        katakanaImgURL: "path/to/ホ/image",
    },
    {
        romaji: "bo",
        hiragana: "ぼ",
        hiraganaImgURL: "path/to/ぼ/image",
        katakana: "ボ",
        katakanaImgURL: "path/to/ボ/image",
    },
    {
        romaji: "po",
        hiragana: "ぽ",
        hiraganaImgURL: "path/to/ぽ/image",
        katakana: "ポ",
        katakanaImgURL: "path/to/ポ/image",
    },
    {
        romaji: "ma",
        hiragana: "ま",
        hiraganaImgURL: "path/to/ま/image",
        katakana: "マ",
        katakanaImgURL: "path/to/マ/image",
    },
    {
        romaji: "mi",
        hiragana: "み",
        hiraganaImgURL: "path/to/み/image",
        katakana: "ミ",
        katakanaImgURL: "path/to/ミ/image",
    },
    {
        romaji: "mu",
        hiragana: "む",
        hiraganaImgURL: "path/to/む/image",
        katakana: "ム",
        katakanaImgURL: "path/to/ム/image",
    },
    {
        romaji: "me",
        hiragana: "め",
        hiraganaImgURL: "path/to/め/image",
        katakana: "メ",
        katakanaImgURL: "path/to/メ/image",
    },
    {
        romaji: "mo",
        hiragana: "も",
        hiraganaImgURL: "path/to/も/image",
        katakana: "モ",
        katakanaImgURL: "path/to/モ/image",
    },
    {
        romaji: "ya",
        hiragana: "や",
        hiraganaImgURL: "path/to/や/image",
        katakana: "ヤ",
        katakanaImgURL: "path/to/ヤ/image",
    },
    {
        romaji: "yu",
        hiragana: "ゆ",
        hiraganaImgURL: "path/to/ゆ/image",
        katakana: "ユ",
        katakanaImgURL: "path/to/ユ/image",
    },
    {
        romaji: "yo",
        hiragana: "よ",
        hiraganaImgURL: "path/to/よ/image",
        katakana: "ヨ",
        katakanaImgURL: "path/to/ヨ/image",
    },
    {
        romaji: "ra",
        hiragana: "ら",
        hiraganaImgURL: "path/to/ら/image",
        katakana: "ラ",
        katakanaImgURL: "path/to/ラ/image",
    },
    {
        romaji: "ri",
        hiragana: "り",
        hiraganaImgURL: "path/to/り/image",
        katakana: "リ",
        katakanaImgURL: "path/to/リ/image",
    },
    {
        romaji: "ru",
        hiragana: "る",
        hiraganaImgURL: "path/to/る/image",
        katakana: "ル",
        katakanaImgURL: "path/to/ル/image",
    },
    {
        romaji: "re",
        hiragana: "れ",
        hiraganaImgURL: "path/to/れ/image",
        katakana: "レ",
        katakanaImgURL: "path/to/レ/image",
    },
    {
        romaji: "ro",
        hiragana: "ろ",
        hiraganaImgURL: "path/to/ろ/image",
        katakana: "ロ",
        katakanaImgURL: "path/to/ロ/image",
    },
    {
        romaji: "wa",
        hiragana: "わ",
        hiraganaImgURL: "path/to/わ/image",
        katakana: "ワ",
        katakanaImgURL: "path/to/ワ/image",
    },
    {
        romaji: "wo",
        hiragana: "を",
        hiraganaImgURL: "path/to/を/image",
        katakana: "ヲ",
        katakanaImgURL: "path/to/ヲ/image",
    },
    {
        romaji: "n",
        hiragana: "ん",
        hiraganaImgURL: "path/to/ん/image",
        katakana: "ン",
        katakanaImgURL: "path/to/ン/image",
    }
];


export default choiceData;