const choices = {
    'あ行': ['a', 'i', 'u', 'e', 'o'],
    'か行': ['ka', 'ki', 'ku', 'ke', 'ko'],
    'が行': ['ga', 'gi', 'gu', 'ge', 'go'],
    'さ行': ['sa', 'shi', 'su', 'se', 'so'],
    'ざ行': ['za', 'ji', 'zu', 'ze', 'zo'],
    'た行': ['ta', 'chi', 'tsu', 'te', 'to'],
    'だ行': ['da', 'ji', 'zu', 'de', 'do'],
    'な行': ['na', 'ni', 'nu', 'ne', 'no'],
    'は行': ['ha', 'hi', 'fu', 'he', 'ho'],
    'ば行': ['ba', 'bi', 'bu', 'be', 'bo'],
    'ぱ行': ['pa', 'pi', 'pu', 'pe', 'po'],
    'ま行': ['ma', 'mi', 'mu', 'me', 'mo'],
    'や行': ['ya', 'yu', 'yo'],
    'ら行': ['ra', 'ri', 'ru', 're', 'ro'],
    'わ行': ['wa', 'wo', 'n'],
};